# Generated by Django 5.0.1 on 2024-01-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(null=True, related_name="tags", to="post.tag"),
        ),
    ]
