# Generated by Django 5.0.1 on 2024-01-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="post.tag"
            ),
        ),
    ]
