# Generated by Django 5.0.1 on 2024-01-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
    ]
