# Generated by Django 5.0.1 on 2024-02-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_savedpost_created_at_savedpost_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedpost",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="savedpost",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="savedpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
