# Generated by Django 5.0.1 on 2024-01-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(related_name="tags", to="post.tag"),
        ),
    ]
