# Generated by Django 5.0.1 on 2024-01-29 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_alter_post_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
