# Generated by Django 5.0.1 on 2024-02-04 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0008_alter_stream_options_postimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="picture",
        ),
    ]
