# Generated by Django 5.0.1 on 2024-02-04 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0009_remove_post_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tag",
            new_name="tags",
        ),
    ]
