# Generated by Django 5.0.1 on 2024-02-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
        ("userAuth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favourite",
            field=models.ManyToManyField(
                blank=True, related_name="favourite", to="post.post"
            ),
        ),
    ]
