# Generated by Django 5.0.1 on 2024-02-10 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
        ("userAuth", "0003_savedpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedpost",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_post",
                to="post.post",
            ),
        ),
        migrations.AlterField(
            model_name="savedpost",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="userAuth.profile",
            ),
        ),
    ]
