# Generated by Django 5.0.1 on 2024-02-10 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0006_alter_savedpost_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavedPost",
        ),
    ]
