# Generated by Django 5.0.1 on 2024-02-18 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0007_delete_savedpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="favourite",
        ),
    ]
